### ISSUE TITLE
[Suggestion] Alternate Steel Beam Recipe?

### ISSUE THREAD

**Issue by VaelophisNyx** [lynkfox/SFMod-VanillaRecipesExtended#1]
Would it be possible to give us a steel beam recipe that isn't 100% trash for its input costs and output rate? Current vanilla one has no alternates and is absurdly expensive, AND slow.

**Comment by lynkfox** [comment]
What do you have in mind and why do you consider current alternatives for Steel Beam to be trash?

**Comment by VaelophisNyx** [comment]
the problem with current steel beams is that you pay 4 steel ingots *per beam*, to get ONE beam, and it is slow as hell while doing so. It's extremely cost and time intensive, to the point that it gets relegated to mk3 belt/lift materials only as soon as you have recipes that use pipes, which all cost less steel ingots to do, and also are faster as a result of pipes being considerably faster to craft. **And to further point out, there are no steel beam alternative recipes**, even among the few mods that add new ones.

personally some sort of "Extruded" Steel Beam recipe would be neat, just cutting down the cost of steel alone would make it much more usable.

**Comment by lynkfox** [comment]
Hmm. Amusing that I missed there were no native vanilla alternates. That
does make it a prime candidate. I'll add it to my list of items I want
alternates for

**Comment by lynkfox** [comment]
As I have stated in the mod description, my goal with these is to be balanced and interesting alternatives.  Ive added one such alt currently: https://github.com/lynkfox/SFMod-VanillaRecipesExtended/blob/main/Documentation/recipe_descriptions/Power%20Overwhelming.md#alternate-pure-steel-beams

and have plans for additional, lower level ones than this in a new milestone I'll be adding in a couple of updates. So for now, closing this out, thanks for the feedback!
